Repository coredac/dataflow, pull requests merged in 2025-08, with the labels that each got.

#108 Enable spatial-only mapping
  include/NeuraDialect/Architecture/Architecture.h
  include/NeuraDialect/Mapping/HeuristicMapping/HeuristicMapping.h
  include/NeuraDialect/Mapping/Mapping.h
  include/NeuraDialect/Mapping/MappingState.h
  include/NeuraDialect/Mapping/mapping_util.h
  lib/NeuraDialect/Architecture/Architecture.cpp
  lib/NeuraDialect/Mapping/HeuristicMapping/HeuristicMapping.cpp
  lib/NeuraDialect/Mapping/Mapping.cpp
  lib/NeuraDialect/Mapping/MappingState.cpp
  lib/NeuraDialect/Mapping/mapping_util.cpp
  lib/NeuraDialect/Transforms/FuseControlFlowPass.cpp
  lib/NeuraDialect/Transforms/MapToAcceleratorPass.cpp
  test/controflow_fuse/simple_loop/simple_loop.mlir
  test/controflow_fuse/simple_loop_reduction/simple_loop_reduction.mlir
  test/mapping_quality/branch_for.mlir
  test/mapping_quality/tiny_loop.mlir
  test/neura/ctrl/branch_for.mlir
Labels: enhancement, new feature

#117 Fix the bug in canonicalize-live-in pass
  lib/NeuraDialect/Transforms/CanonicalizeLiveInPass.cpp
  lib/NeuraDialect/Transforms/FuseControlFlowPass.cpp
  lib/NeuraDialect/Transforms/MapToAcceleratorPass.cpp
  lib/NeuraDialect/Transforms/TransformCtrlToDataFlowPass.cpp
  test/affine2neura/bert/bert_node1/bert_node1.mlir
  test/affine2neura/bert/bert_node28/bert_node28.mlir
  test/controflow_fuse/complex_nested/complex_nested.mlir
  test/controflow_fuse/non_perfect_nested/non_perfect_nested.mlir
  test/controflow_fuse/perfect_nested/perfect_nested.mlir
  test/controflow_fuse/perfect_reduction/perfect_reduction.mlir
  test/controflow_fuse/simple_loop/simple_loop.mlir
  test/controflow_fuse/simple_loop_reduction/simple_loop_reduction.mlir
  test/mapping_quality/branch_for.mlir
  test/mapping_quality/tiny_loop.mlir
  test/neura/ctrl/branch_for.mlir
  test/neura/ctrl/for_with_if.mlir
  test/neura/ctrl/nested_branch.mlir
  test/neura/for_loop/test.mlir
Labels: bug, enhancement

#105 add interpreter dataflow mode
  test/neura/interpreter/basic_operation/add.mlir
  test/neura/interpreter/basic_operation/br.mlir
  test/neura/interpreter/basic_operation/cast.mlir
  test/neura/interpreter/basic_operation/cond_br.mlir
  test/neura/interpreter/basic_operation/ctrl_mov.mlir
  test/neura/interpreter/basic_operation/fadd.mlir
  test/neura/interpreter/basic_operation/fadd_fadd.mlir
  test/neura/interpreter/basic_operation/fcmp.mlir
  test/neura/interpreter/basic_operation/fdiv.mlir
  test/neura/interpreter/basic_operation/fmul.mlir
  test/neura/interpreter/basic_operation/fmul_add.mlir
  test/neura/interpreter/basic_operation/fsub.mlir
  test/neura/interpreter/basic_operation/gep.mlir
  test/neura/interpreter/basic_operation/grant.mlir
  test/neura/interpreter/basic_operation/icmp.mlir
  test/neura/interpreter/basic_operation/load_store.mlir
  test/neura/interpreter/basic_operation/load_store_index.mlir
  test/neura/interpreter/basic_operation/not.mlir
  test/neura/interpreter/basic_operation/or.mlir
  test/neura/interpreter/basic_operation/phi.mlir
  test/neura/interpreter/basic_operation/reserve.mlir
  test/neura/interpreter/basic_operation/sel.mlir
  test/neura/interpreter/basic_operation/sub.mlir
  test/neura/interpreter/basic_operation/vfmul.mlir
  test/neura/interpreter/loop_convert_controlflow_to_dataflow.mlir
  tools/neura-interpreter/neura-interpreter.cpp
Labels: new feature
