Repository coredac/dataflow, pull requests merged in 2025-07, with the labels that each got.

#68 Fix run command syntax and check rules in nested_branch.mlir test
  test/neura/ctrl/nested_branch.mlir
Labels: bug

#73 Enable backtrack mapping strategy
  include/NeuraDialect/Mapping/HeuristicMapping/HeuristicMapping.h
  include/NeuraDialect/Mapping/MappingState.h
  include/NeuraDialect/Mapping/MappingStrategy.h
  lib/NeuraDialect/Architecture/Architecture.cpp
  lib/NeuraDialect/CMakeLists.txt
  lib/NeuraDialect/Mapping/HeuristicMapping/HeuristicMapping.cpp
  lib/NeuraDialect/Mapping/MappingState.cpp
  lib/NeuraDialect/Mapping/MappingStrategy.cpp
  lib/NeuraDialect/Mapping/mapping_util.cpp
  lib/NeuraDialect/Transforms/MapToAcceleratorPass.cpp
  test/neura/ctrl/branch_for.mlir
Labels: bug, new feature

#72 add architecture_spec.yaml file and yaml2json script
  .gitignore
  include/ArchitectureSpec/architecture.json
  include/ArchitectureSpec/architecture.yaml
  include/ArchitectureSpec/yaml2json.py
Labels: new feature

#85 [feature] Enable ctrl to data flow lowering for llvm.func
  lib/NeuraDialect/Transforms/GenerateCodePass.cpp
  lib/NeuraDialect/Transforms/LeveragePredicatedValuePass.cpp
  lib/NeuraDialect/Transforms/TransformCtrlToDataFlowPass.cpp
  test/neura/for_loop/test.mlir
Labels: new feature

#70 Interpreter v1.0.0
  include/NeuraDialect/NeuraOps.td
  test/neura/interpreter/add.mlir
  test/neura/interpreter/basic_operation/add.mlir
  test/neura/interpreter/basic_operation/br.mlir
  test/neura/interpreter/basic_operation/cast.mlir
  test/neura/interpreter/basic_operation/cond_br.mlir
  test/neura/interpreter/basic_operation/ctrl_mov.mlir
  test/neura/interpreter/basic_operation/fadd.mlir
  test/neura/interpreter/basic_operation/fadd_fadd.mlir
  test/neura/interpreter/basic_operation/fcmp.mlir
  test/neura/interpreter/basic_operation/fdiv.mlir
  test/neura/interpreter/basic_operation/fmul.mlir
  test/neura/interpreter/basic_operation/fmul_add.mlir
  test/neura/interpreter/basic_operation/fsub.mlir
  test/neura/interpreter/basic_operation/gep.mlir
  test/neura/interpreter/basic_operation/grant.mlir
  test/neura/interpreter/basic_operation/icmp.mlir
  test/neura/interpreter/basic_operation/interpreter.mlir
  test/neura/interpreter/basic_operation/load_store.mlir
  test/neura/interpreter/basic_operation/load_store_index.mlir
  test/neura/interpreter/basic_operation/not.mlir
  test/neura/interpreter/basic_operation/or.mlir
  test/neura/interpreter/basic_operation/phi.mlir
  test/neura/interpreter/basic_operation/predicated_data.mlir
  test/neura/interpreter/basic_operation/reserve.mlir
  test/neura/interpreter/basic_operation/sel.mlir
  test/neura/interpreter/basic_operation/sub.mlir
  test/neura/interpreter/basic_operation/vfmul.mlir
  test/neura/interpreter/lower_and_interpret.mlir
  test/neura/interpreter/lower_and_interpret_subf.mlir
  tools/neura-interpreter/neura-interpreter.cpp
Labels: new feature

#86 Create a neura canonicalize pass
  .github/workflows/main.yml
  CMakeLists.txt
  README.md
  include/NeuraDialect/NeuraOps.td
  include/NeuraDialect/NeuraPasses.h
  include/NeuraDialect/NeuraPasses.td
  lib/Conversion/ArithToNeura/ArithToNeuraPass.cpp
  lib/NeuraDialect/Transforms/CMakeLists.txt
  lib/NeuraDialect/Transforms/CanonicalizeLiveInPass.cpp
  lib/NeuraDialect/Transforms/FusePatternsPass.cpp
  lib/NeuraDialect/Transforms/TransformCtrlToDataFlowPass.cpp
  test/affine2neura/bert/bert_node0/bert_node0.mlir
  test/affine2neura/bert/bert_node1/bert_node1.mlir
  test/affine2neura/bert/bert_node2/bert_node2.mlir
  test/affine2neura/bert/bert_node28/bert_node28.mlir
  test/affine2neura/bert/bert_node3/bert_node3.mlir
  test/affine2neura/bert/bert_node8/bert_node8.mlir
  test/affine2neura/bert/bert_node9/bert_node9.mlir
  test/controflow_fuse/complex_nested/complex_nested.mlir
  test/controflow_fuse/non_perfect_nested/non_perfect_nested.mlir
  test/controflow_fuse/perfect_nested/perfect_nested.mlir
  test/controflow_fuse/perfect_reduction/perfect_reduction.mlir
  test/controflow_fuse/simpleloop/simpleloop.mlir
  test/lit.cfg.in
  test/neura/ctrl/branch.mlir
  test/neura/ctrl/branch_for.mlir
  test/neura/ctrl/branch_with_and_without_arg.mlir
  test/neura/ctrl/branch_without_arg.mlir
  test/neura/ctrl/nested_branch.mlir
  test/neura/for_loop/test.mlir
Labels: new feature

#91 Remove non-sense neura::cast ops
  include/NeuraDialect/NeuraPasses.h
  include/NeuraDialect/NeuraPasses.td
  lib/NeuraDialect/Transforms/CMakeLists.txt
  lib/NeuraDialect/Transforms/CanonicalizeCastPass.cpp
  test/controflow_fuse/perfect_nested/perfect_nested.mlir
  test/controflow_fuse/perfect_reduction/perfect_reduction.mlir
  test/controflow_fuse/simpleloop/simpleloop.mlir
Labels: new feature

#93 Prepare Function Unit and Registers for mapping
  include/NeuraDialect/Architecture/Architecture.h
  lib/NeuraDialect/Architecture/Architecture.cpp
  lib/NeuraDialect/Mapping/mapping_util.cpp
Labels: new feature

#98 Add some heuristics into mapping
  include/NeuraDialect/Mapping/HeuristicMapping/HeuristicMapping.h
  include/NeuraDialect/Mapping/MappingStrategy.h
  include/NeuraDialect/Mapping/mapping_util.h
  lib/NeuraDialect/Mapping/HeuristicMapping/HeuristicMapping.cpp
  lib/NeuraDialect/Mapping/mapping_util.cpp
  lib/NeuraDialect/Transforms/MapToAcceleratorPass.cpp
  test/neura/ctrl/branch_for.mlir
Labels: enhancement, help wanted, new feature

#100 Revise loop_conrtol and replace grant_always operations
  include/NeuraDialect/NeuraOps.td
  lib/NeuraDialect/Mapping/mapping_util.cpp
  lib/NeuraDialect/Transforms/FuseControlFlowPass.cpp
  lib/NeuraDialect/Transforms/FusePatternsPass.cpp
  lib/NeuraDialect/Transforms/MapToAcceleratorPass.cpp
  lib/NeuraDialect/Transforms/TransformCtrlToDataFlowPass.cpp
  test/affine2neura/bert/bert_node1/bert_node1.mlir
  test/affine2neura/bert/bert_node28/bert_node28.mlir
  test/controflow_fuse/complex_nested/complex_nested.mlir
  test/controflow_fuse/non_perfect_nested/non_perfect_nested.mlir
  test/controflow_fuse/perfect_nested/perfect_nested.mlir
  test/controflow_fuse/perfect_reduction/perfect_reduction.mlir
  test/controflow_fuse/simple_loop/simple_loop.cpp
  test/controflow_fuse/simple_loop/simple_loop.mlir
  test/controflow_fuse/simple_loop_reduction/simple_loop_reduction.cpp
  test/controflow_fuse/simple_loop_reduction/simple_loop_reduction.mlir
  test/controflow_fuse/simpleloop/simpleloop.mlir
  test/neura/ctrl/branch_for.mlir
  test/neura/ctrl/nested_branch.mlir
  test/neura/for_loop/test.mlir
Labels: new feature
